---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: :verify_peer

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[php-modules::default]
    attributes:
      php-modules:
        modules:
          curl: true
          gd: true
          imagick: true
          imap: true
          ioncube: true
          mcrypt: true
